import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("com.android.application")          // AGP 9: includes Kotlin support
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
}

// FCM needs app/google-services.json from your Firebase project (design doc 8).
// Without it the app still builds and runs; push registration is simply skipped.
if (file("google-services.json").exists()) apply(plugin = "com.google.gms.google-services")

fun prop(name: String, default: String = "") = (project.findProperty(name) as String?)?.trim() ?: default

// ---- Trusted certificates bundled into DEBUG builds ----------------------------------------
// The trial server (healoo-backend, LAN profile) uses its own certificate authority. Debug builds
// carry that CA inside the app, so devices don't need it installed. Collected from, in order:
//   1. healoo.trustedCaFile=<path to a .crt/.pem>        (gradle.properties or ~/.gradle/gradle.properties)
//   2. every .crt / .pem / .cer file in android/certs/
//   3. the trial server's folder next to the app:
//        ../../Server/deploy/lan/healoo-local-ca.crt          (Healoo repository layout)
//        ../../healoo-backend/deploy/lan/healoo-local-ca.crt  (separate zips unpacked side by side)
// Release builds never include these: they only trust the system's public certificate authorities.
val bundledCaFiles: List<File> = buildList {
    prop("healoo.trustedCaFile").takeIf { it.isNotEmpty() }?.let { add(file(it)) }
    rootProject.file("certs").listFiles { f -> f.extension.lowercase() in setOf("crt", "pem", "cer") }
        ?.sortedBy { it.name }?.let { addAll(it) }
    add(rootProject.file("../../Server/deploy/lan/healoo-local-ca.crt"))
    add(rootProject.file("../../healoo-backend/deploy/lan/healoo-local-ca.crt"))
}.filter { it.isFile }.distinctBy { it.canonicalPath }

/** Writes res/xml/network_security_config_dev.xml and copies the CA files to res/raw/. */
abstract class HealooDevNetworkConfig : DefaultTask() {
    @get:InputFiles @get:PathSensitive(PathSensitivity.NAME_ONLY)
    abstract val caFiles: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val out = outputDir.get().asFile
        out.deleteRecursively()
        File(out, "xml").mkdirs()
        val lines = StringBuilder()
        caFiles.files.sortedBy { it.name }.forEachIndexed { i, ca ->
            File(out, "raw").mkdirs()
            val name = "healoo_trusted_ca_${i + 1}"          // raw resource names: lowercase, digits, _
            ca.copyTo(File(out, "raw/$name.crt"), overwrite = true)
            lines.append("\n            <certificates src=\"@raw/$name\" />  <!-- ${ca.name} -->")
            logger.lifecycle("Healoo debug build trusts bundled certificate: ${ca.absolutePath}")
        }
        if (lines.isEmpty()) {
            logger.warn("Healoo: no trial-server certificate bundled. Put healoo-local-ca.crt in android/certs/ " +
                "or set healoo.trustedCaFile, or install it on the device.")
        }
        File(out, "xml/network_security_config_dev.xml").writeText(
            """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by the healooDevNetworkConfig task (debug builds only). Do not edit. -->
<network-security-config>
    <base-config>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />$lines
        </trust-anchors>
    </base-config>
</network-security-config>
"""
        )
    }
}

val healooDevNetworkConfig = tasks.register<HealooDevNetworkConfig>("healooDevNetworkConfig") {
    caFiles.from(bundledCaFiles)
    outputDir.set(layout.buildDirectory.dir("generated/healoo/devNetworkConfig"))
}

/** Bundles WUI/page-operations.json (bottom-bar operations, shared with iOS) as an asset. */
abstract class HealooSharedAssets : DefaultTask() {
    @get:InputFile @get:PathSensitive(PathSensitivity.NAME_ONLY)
    abstract val operationsFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun copy() {
        val src = operationsFile.get().asFile
        src.copyTo(File(outputDir.get().asFile, src.name), overwrite = true)
    }
}

val healooSharedAssets = tasks.register<HealooSharedAssets>("healooSharedAssets") {
    operationsFile.set(rootProject.file("../page-operations.json"))
    outputDir.set(layout.buildDirectory.dir("generated/healoo/sharedAssets"))
}

androidComponents {
    onVariants(selector().withBuildType("debug")) { variant ->
        variant.sources.res?.addGeneratedSourceDirectory(healooDevNetworkConfig, HealooDevNetworkConfig::outputDir)
    }
    onVariants { variant ->
        variant.sources.assets?.addGeneratedSourceDirectory(healooSharedAssets, HealooSharedAssets::outputDir)
    }
}

val auth0Domain = prop("healoo.auth0.domain")
val auth0Scheme = "healoo"

android {
    namespace = "com.healoo.app"
    compileSdk = 36        // required by the Compose/AndroidX versions below; needs SDK Platform 36

    defaultConfig {
        applicationId = "com.healoo.app"
        minSdk = 29
        targetSdk = 35         // runtime behaviour unchanged (Android 15)
        versionCode = 4
        versionName = "0.4-trial"

        buildConfigField("String", "API_BASE_URL", "\"${prop("healoo.apiBaseUrl", "https://10.0.2.2/")}\"")
        buildConfigField("boolean", "USE_FAKE_DATA", prop("healoo.useFakeData", "true"))
        // Developer sign-in against the trial server (backend AUTH_MODE=dev). Forced off in release.
        buildConfigField("boolean", "DEV_SIGN_IN", prop("healoo.devSignIn", "true"))
        buildConfigField("String", "AUTH0_DOMAIN", "\"$auth0Domain\"")
        buildConfigField("String", "AUTH0_CLIENT_ID", "\"${prop("healoo.auth0.clientId")}\"")
        buildConfigField("String", "AUTH0_AUDIENCE", "\"${prop("healoo.auth0.audience")}\"")
        buildConfigField("String", "AUTH0_SCHEME", "\"$auth0Scheme\"")

        // Required by the Auth0 SDK's redirect activity. Callback URL to register in Auth0:
        //   healoo://<domain>/android/com.healoo.app/callback
        manifestPlaceholders["auth0Domain"] = auth0Domain.ifEmpty { "not-configured.invalid" }
        manifestPlaceholders["auth0Scheme"] = auth0Scheme
    }

    // Release signing. Keep the keystore and passwords OUT of the project: put them in
    // ~/.gradle/gradle.properties (or pass -P on the command line):
    //   healoo.signing.storeFile=C:/keys/healoo-release.jks
    //   healoo.signing.storePassword=...   healoo.signing.keyAlias=healoo   healoo.signing.keyPassword=...
    // Without them, assembleRelease produces an unsigned APK that phones won't install.
    val releaseStore = prop("healoo.signing.storeFile")
    signingConfigs {
        if (releaseStore.isNotEmpty()) create("release") {
            storeFile = file(releaseStore)
            storePassword = prop("healoo.signing.storePassword")
            keyAlias = prop("healoo.signing.keyAlias", "healoo")
            keyPassword = prop("healoo.signing.keyPassword")
        }
    }

    buildTypes {
        // Debug: system + user-installed + bundled trial-server certificates (generated, see above).
        debug {
            manifestPlaceholders["networkConfig"] = "@xml/network_security_config_dev"
            // healoo.minifyDebug=true: shrink the debug build like release, to test R8 against the
            // trial server (release builds have developer sign-in off).
            if (prop("healoo.minifyDebug") == "true") {
                isMinifyEnabled = true
                isShrinkResources = true
                proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            }
        }
        release {
            // R8: removes unused code and resources and optimises the rest (APK ~70 MB -> a few MB).
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            manifestPlaceholders["networkConfig"] = "@xml/network_security_config_release"
            buildConfigField("boolean", "DEV_SIGN_IN", "false")
            if (releaseStore.isNotEmpty()) signingConfig = signingConfigs.getByName("release")
        }
    }

    buildFeatures { compose = true; buildConfig = true }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

// Replaces android { kotlinOptions { } }, which AGP 9 removed.
kotlin {
    compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2025.08.01")
    implementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.material3:material3")
    // Core icons only; the others the app uses are copied into ui/icons (the extended set is ~34 MB).
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.compose.ui:ui-tooling-preview")
    debugImplementation("androidx.compose.ui:ui-tooling")

    implementation("androidx.activity:activity-compose:1.10.1")
    implementation("androidx.navigation:navigation-compose:2.9.3")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.9.2")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.9.2")
    implementation("androidx.lifecycle:lifecycle-process:2.9.2")

    implementation("io.coil-kt:coil-compose:2.7.0")
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-kotlinx-serialization:2.11.0")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.8.1")

    // Auth0 login (doc 5)
    implementation("com.auth0.android:auth0:2.10.2")
    // FCM push (doc 8)
    implementation(platform("com.google.firebase:firebase-bom:33.3.0"))
    implementation("com.google.firebase:firebase-messaging")
    // QR: scan with Google code scanner (no camera permission needed), draw with ZXing
    implementation("com.google.android.gms:play-services-code-scanner:16.1.0")
    implementation("com.google.zxing:core:3.5.3")

    testImplementation("junit:junit:4.13.2")
}
